// Mocks generated by Mockito 5.4.6 from annotations
// in nova/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:nova/core/errors/failures.dart' as _i8;
import 'package:nova/data/datasources/remote/station_remote_data_source.dart'
    as _i3;
import 'package:nova/data/models/station_model.dart' as _i2;
import 'package:nova/data/models/water_level_point_model.dart' as _i5;
import 'package:nova/domain/entities/station.dart' as _i9;
import 'package:nova/domain/entities/water_level_point.dart' as _i11;
import 'package:nova/domain/repositories/station_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStationModel_0 extends _i1.SmartFake implements _i2.StationModel {
  _FakeStationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStationRemoteDataSource extends _i1.Mock
    implements _i3.StationRemoteDataSource {
  MockStationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.StationModel>> getStations({
    String? state,
    String? district,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStations,
          [],
          {
            #state: state,
            #district: district,
            #status: status,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.StationModel>>.value(<_i2.StationModel>[]),
      ) as _i4.Future<List<_i2.StationModel>>);

  @override
  _i4.Future<_i2.StationModel> getStationDetail(String? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationDetail,
          [stationId],
        ),
        returnValue: _i4.Future<_i2.StationModel>.value(_FakeStationModel_0(
          this,
          Invocation.method(
            #getStationDetail,
            [stationId],
          ),
        )),
      ) as _i4.Future<_i2.StationModel>);

  @override
  _i4.Future<List<_i5.WaterLevelPointModel>> getStationTimeSeries(
    String? stationId,
    DateTime? from,
    DateTime? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationTimeSeries,
          [
            stationId,
            from,
            to,
          ],
        ),
        returnValue: _i4.Future<List<_i5.WaterLevelPointModel>>.value(
            <_i5.WaterLevelPointModel>[]),
      ) as _i4.Future<List<_i5.WaterLevelPointModel>>);
}

/// A class which mocks [StationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStationRepository extends _i1.Mock implements _i6.StationRepository {
  MockStationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.Either<_i8.AppFailure, List<_i9.Station>>> getStations({
    String? state,
    String? district,
    String? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStations,
          [],
          {
            #state: state,
            #district: district,
            #status: status,
          },
        ),
        returnValue:
            _i4.Future<_i7.Either<_i8.AppFailure, List<_i9.Station>>>.value(
                _i10.dummyValue<_i7.Either<_i8.AppFailure, List<_i9.Station>>>(
          this,
          Invocation.method(
            #getStations,
            [],
            {
              #state: state,
              #district: district,
              #status: status,
            },
          ),
        )),
      ) as _i4.Future<_i7.Either<_i8.AppFailure, List<_i9.Station>>>);

  @override
  _i4.Future<_i7.Either<_i8.AppFailure, _i9.Station>> getStationDetail(
          String? stationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStationDetail,
          [stationId],
        ),
        returnValue: _i4.Future<_i7.Either<_i8.AppFailure, _i9.Station>>.value(
            _i10.dummyValue<_i7.Either<_i8.AppFailure, _i9.Station>>(
          this,
          Invocation.method(
            #getStationDetail,
            [stationId],
          ),
        )),
      ) as _i4.Future<_i7.Either<_i8.AppFailure, _i9.Station>>);

  @override
  _i4.Future<_i7.Either<_i8.AppFailure, List<_i11.WaterLevelPoint>>>
      getStationTimeSeries(
    String? stationId,
    DateTime? from,
    DateTime? to,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getStationTimeSeries,
              [
                stationId,
                from,
                to,
              ],
            ),
            returnValue: _i4.Future<
                    _i7
                    .Either<_i8.AppFailure, List<_i11.WaterLevelPoint>>>.value(
                _i10.dummyValue<
                    _i7.Either<_i8.AppFailure, List<_i11.WaterLevelPoint>>>(
              this,
              Invocation.method(
                #getStationTimeSeries,
                [
                  stationId,
                  from,
                  to,
                ],
              ),
            )),
          ) as _i4
              .Future<_i7.Either<_i8.AppFailure, List<_i11.WaterLevelPoint>>>);
}
